"""Added an association table customer_restaurant_review

Revision ID: 8100476e4caf
Revises: f2a2615480a6
Create Date: 2023-12-19 14:36:29.955605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8100476e4caf'
down_revision: Union[str, None] = 'f2a2615480a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
